### PR TITLE
Upgrade to sentry 8.12.0

### PR DESCRIPTION
**Pull request by bremac**
Pull in the changes @jbrownsc made directly on the EC2 instance. Also moves the nine deprecated settings from sentry.conf.py to config.yaml so that I no longer get spammed with warnings whenever I log in

### CODE REVIEW

**Review by jbrownsc — APPROVED** [review]
Very nice!

**Comment by jbrownsc** [comment]
@bremac Some of the dependencies also required clang >= 3.4.  I can throw that in here too.

**Comment by bremac** [comment]
Nah, I got it. I've added all of the dependencies required to build a new system from scratch.

**Comment by jbrownsc** [comment]
This looks good to me!

**Pull request merged**
